
package br.org.abrasf.nfse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "nfse", targetNamespace = "http://nfse.abrasf.org.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Nfse {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.abrasf.nfse.Output
     */
    @WebMethod(operationName = "CancelarNfse", action = "http://nfse.abrasf.org.br/CancelarNfse")
    @WebResult(name = "CancelarNfseResponse", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
    public Output cancelarNfse(
        @WebParam(name = "CancelarNfseRequest", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
        Input parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.abrasf.nfse.Output
     */
    @WebMethod(operationName = "ConsultarLoteRps", action = "http://nfse.abrasf.org.br/ConsultarLoteRps")
    @WebResult(name = "ConsultarLoteRpsResponse", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
    public Output consultarLoteRps(
        @WebParam(name = "ConsultarLoteRpsRequest", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
        Input parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.abrasf.nfse.Output
     */
    @WebMethod(operationName = "ConsultarNfseServicoPrestado", action = "http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado")
    @WebResult(name = "ConsultarNfseServicoPrestadoResponse", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
    public Output consultarNfseServicoPrestado(
        @WebParam(name = "ConsultarNfseServicoPrestadoRequest", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
        Input parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.abrasf.nfse.Output
     */
    @WebMethod(operationName = "ConsultarNfseServicoTomado", action = "http://nfse.abrasf.org.br/ConsultarNfseServicoTomado")
    @WebResult(name = "ConsultarNfseServicoTomadoResponse", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
    public Output consultarNfseServicoTomado(
        @WebParam(name = "ConsultarNfseServicoTomadoRequest", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
        Input parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.abrasf.nfse.Output
     */
    @WebMethod(operationName = "ConsultarNfsePorFaixa", action = "http://nfse.abrasf.org.br/ConsultarNfsePorFaixa")
    @WebResult(name = "ConsultarNfsePorFaixaResponse", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
    public Output consultarNfsePorFaixa(
        @WebParam(name = "ConsultarNfsePorFaixaRequest", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
        Input parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.abrasf.nfse.Output
     */
    @WebMethod(operationName = "ConsultarNfsePorRps", action = "http://nfse.abrasf.org.br/ConsultarNfsePorRps")
    @WebResult(name = "ConsultarNfsePorRpsResponse", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
    public Output consultarNfsePorRps(
        @WebParam(name = "ConsultarNfsePorRpsRequest", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
        Input parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.abrasf.nfse.Output
     */
    @WebMethod(operationName = "RecepcionarLoteRps", action = "http://nfse.abrasf.org.br/RecepcionarLoteRps")
    @WebResult(name = "RecepcionarLoteRpsResponse", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
    public Output recepcionarLoteRps(
        @WebParam(name = "RecepcionarLoteRpsRequest", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
        Input parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.abrasf.nfse.Output
     */
    @WebMethod(operationName = "GerarNfse", action = "http://nfse.abrasf.org.br/GerarNfse")
    @WebResult(name = "GerarNfseResponse", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
    public Output gerarNfse(
        @WebParam(name = "GerarNfseRequest", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
        Input parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.abrasf.nfse.Output
     */
    @WebMethod(operationName = "SubstituirNfse", action = "http://nfse.abrasf.org.br/SubstituirNfse")
    @WebResult(name = "SubstituirNfseResponse", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
    public Output substituirNfse(
        @WebParam(name = "SubstituirNfseRequest", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
        Input parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.org.abrasf.nfse.Output
     */
    @WebMethod(operationName = "RecepcionarLoteRpsSincrono", action = "http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono")
    @WebResult(name = "RecepcionarLoteRpsSincronoResponse", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
    public Output recepcionarLoteRpsSincrono(
        @WebParam(name = "RecepcionarLoteRpsSincronoRequest", targetNamespace = "http://nfse.abrasf.org.br", partName = "parameters")
        Input parameters);

}
