package br.com.tti.sefaz.ttirec.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "TTIWSEndpointService", targetNamespace = "http://wsendpoint.sefaz.tti.com.br/", wsdlLocation = "http://192.168.0.148:8080/TTIWSEndpoint?wsdl")
public class TTIWSEndpointService extends Service {

	private final static URL TTIWSENDPOINTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(br.com.tti.sefaz.ttirec.wsclient.TTIWSEndpointService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = br.com.tti.sefaz.ttirec.wsclient.TTIWSEndpointService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://192.168.0.148:8080/TTIWSEndpoint?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.0.148:8080/TTIWSEndpoint?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		TTIWSENDPOINTSERVICE_WSDL_LOCATION = url;
	}

	public TTIWSEndpointService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TTIWSEndpointService() {
		super(TTIWSENDPOINTSERVICE_WSDL_LOCATION, new QName(
				"http://wsendpoint.sefaz.tti.com.br/", "TTIWSEndpointService"));
	}

	/**
	 * 
	 * @return returns TTIWSEndpoint
	 */
	@WebEndpoint(name = "TTIWSEndpointPort")
	public TTIWSEndpoint getTTIWSEndpointPort() {
		return super.getPort(new QName("http://wsendpoint.sefaz.tti.com.br/",
				"TTIWSEndpointPort"), TTIWSEndpoint.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns TTIWSEndpoint
	 */
	@WebEndpoint(name = "TTIWSEndpointPort")
	public TTIWSEndpoint getTTIWSEndpointPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://wsendpoint.sefaz.tti.com.br/",
				"TTIWSEndpointPort"), TTIWSEndpoint.class, features);
	}

}
