//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 11:09:48 AM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/WsNFe2/lote")
package br.com.tti.sefaz.nfes.schemas.ginfes;

