//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 11:09:48 AM BRST 
//


package br.com.tti.sefaz.nfes.schemas.ginfes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Chave de identificação para Substituição de uma NFSe.
 * 
 * <p>Java class for tpChaveSubstituicaoNFSe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpChaveSubstituicaoNFSe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InscricaoPrestador" type="{http://localhost:8080/WsNFe2/tp}tpInscricaoMunicipal"/>
 *         &lt;element name="CPFCNPJTomador" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
 *         &lt;element name="NumeroNFSeSubstituida" type="{http://localhost:8080/WsNFe2/tp}tpNumero"/>
 *         &lt;element name="DataEmissaoNFSeSubstituida" type="{http://localhost:8080/WsNFe2/tp}tpData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpChaveSubstituicaoNFSe", propOrder = {
    "inscricaoPrestador",
    "cpfcnpjTomador",
    "numeroNFSeSubstituida",
    "dataEmissaoNFSeSubstituida"
})
public class TpChaveSubstituicaoNFSe {

    @XmlElement(name = "InscricaoPrestador")
    protected long inscricaoPrestador;
    @XmlElement(name = "CPFCNPJTomador", required = true)
    protected String cpfcnpjTomador;
    @XmlElement(name = "NumeroNFSeSubstituida")
    protected int numeroNFSeSubstituida;
    @XmlElement(name = "DataEmissaoNFSeSubstituida", required = true)
    protected XMLGregorianCalendar dataEmissaoNFSeSubstituida;

    /**
     * Gets the value of the inscricaoPrestador property.
     * 
     */
    public long getInscricaoPrestador() {
        return inscricaoPrestador;
    }

    /**
     * Sets the value of the inscricaoPrestador property.
     * 
     */
    public void setInscricaoPrestador(long value) {
        this.inscricaoPrestador = value;
    }

    /**
     * Gets the value of the cpfcnpjTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPFCNPJTomador() {
        return cpfcnpjTomador;
    }

    /**
     * Sets the value of the cpfcnpjTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPFCNPJTomador(String value) {
        this.cpfcnpjTomador = value;
    }

    /**
     * Gets the value of the numeroNFSeSubstituida property.
     * 
     */
    public int getNumeroNFSeSubstituida() {
        return numeroNFSeSubstituida;
    }

    /**
     * Sets the value of the numeroNFSeSubstituida property.
     * 
     */
    public void setNumeroNFSeSubstituida(int value) {
        this.numeroNFSeSubstituida = value;
    }

    /**
     * Gets the value of the dataEmissaoNFSeSubstituida property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataEmissaoNFSeSubstituida() {
        return dataEmissaoNFSeSubstituida;
    }

    /**
     * Sets the value of the dataEmissaoNFSeSubstituida property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataEmissaoNFSeSubstituida(XMLGregorianCalendar value) {
        this.dataEmissaoNFSeSubstituida = value;
    }

}
