//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 11:09:48 AM BRST 
//


package br.com.tti.sefaz.nfes.schemas.ginfes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Tipo que define a chave identificadora de um RPS.
 * 
 * <p>Java class for tpChaveRPS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpChaveRPS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InscricaoPrestador" type="{http://localhost:8080/WsNFe2/tp}tpInscricaoMunicipal"/>
 *         &lt;element name="SerieRPS" type="{http://localhost:8080/WsNFe2/tp}tpSerieRPS"/>
 *         &lt;element name="NumeroRPS" type="{http://localhost:8080/WsNFe2/tp}tpNumero"/>
 *         &lt;element name="DataEmissaoRPS" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="RazaoSocialPrestador" type="{http://localhost:8080/WsNFe2/tp}tpRazaoSocial"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpChaveRPS", propOrder = {
    "inscricaoPrestador",
    "serieRPS",
    "numeroRPS",
    "dataEmissaoRPS",
    "razaoSocialPrestador"
})
public class TpChaveRPS {

    @XmlElement(name = "InscricaoPrestador")
    protected long inscricaoPrestador;
    @XmlElement(name = "SerieRPS", required = true)
    protected TpSerieRPS serieRPS;
    @XmlElement(name = "NumeroRPS")
    protected int numeroRPS;
    @XmlElement(name = "DataEmissaoRPS", required = true)
    protected XMLGregorianCalendar dataEmissaoRPS;
    @XmlElement(name = "RazaoSocialPrestador", required = true)
    protected String razaoSocialPrestador;

    /**
     * Gets the value of the inscricaoPrestador property.
     * 
     */
    public long getInscricaoPrestador() {
        return inscricaoPrestador;
    }

    /**
     * Sets the value of the inscricaoPrestador property.
     * 
     */
    public void setInscricaoPrestador(long value) {
        this.inscricaoPrestador = value;
    }

    /**
     * Gets the value of the serieRPS property.
     * 
     * @return
     *     possible object is
     *     {@link TpSerieRPS }
     *     
     */
    public TpSerieRPS getSerieRPS() {
        return serieRPS;
    }

    /**
     * Sets the value of the serieRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpSerieRPS }
     *     
     */
    public void setSerieRPS(TpSerieRPS value) {
        this.serieRPS = value;
    }

    /**
     * Gets the value of the numeroRPS property.
     * 
     */
    public int getNumeroRPS() {
        return numeroRPS;
    }

    /**
     * Sets the value of the numeroRPS property.
     * 
     */
    public void setNumeroRPS(int value) {
        this.numeroRPS = value;
    }

    /**
     * Gets the value of the dataEmissaoRPS property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataEmissaoRPS() {
        return dataEmissaoRPS;
    }

    /**
     * Sets the value of the dataEmissaoRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataEmissaoRPS(XMLGregorianCalendar value) {
        this.dataEmissaoRPS = value;
    }

    /**
     * Gets the value of the razaoSocialPrestador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazaoSocialPrestador() {
        return razaoSocialPrestador;
    }

    /**
     * Sets the value of the razaoSocialPrestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazaoSocialPrestador(String value) {
        this.razaoSocialPrestador = value;
    }

}
