//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 11:09:48 AM BRST 
//


package br.com.tti.sefaz.nfes.schemas.ginfes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo que representa a chave de uma NFSe e a Chave do RPS que a mesma substitui.
 * 
 * <p>Java class for tpChaveNFeRPS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpChaveNFeRPS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChaveNFe" type="{http://localhost:8080/WsNFe2/tp}tpChaveNFe" minOccurs="0"/>
 *         &lt;element name="ChaveRPS" type="{http://localhost:8080/WsNFe2/tp}tpChaveRPS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpChaveNFeRPS", propOrder = {
    "chaveNFe",
    "chaveRPS"
})
public class TpChaveNFeRPS {

    @XmlElement(name = "ChaveNFe")
    protected TpChaveNFe chaveNFe;
    @XmlElement(name = "ChaveRPS")
    protected TpChaveRPS chaveRPS;

    /**
     * Gets the value of the chaveNFe property.
     * 
     * @return
     *     possible object is
     *     {@link TpChaveNFe }
     *     
     */
    public TpChaveNFe getChaveNFe() {
        return chaveNFe;
    }

    /**
     * Sets the value of the chaveNFe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpChaveNFe }
     *     
     */
    public void setChaveNFe(TpChaveNFe value) {
        this.chaveNFe = value;
    }

    /**
     * Gets the value of the chaveRPS property.
     * 
     * @return
     *     possible object is
     *     {@link TpChaveRPS }
     *     
     */
    public TpChaveRPS getChaveRPS() {
        return chaveRPS;
    }

    /**
     * Sets the value of the chaveRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpChaveRPS }
     *     
     */
    public void setChaveRPS(TpChaveRPS value) {
        this.chaveRPS = value;
    }

}
