//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 11:09:48 AM BRST 
//


package br.com.tti.sefaz.nfes.schemas.ginfes;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * NFSe de retorno de consulta.
 * 
 * <p>Java class for tpConsultaNFSe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpConsultaNFSe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InscricaoPrestador" type="{http://localhost:8080/WsNFe2/tp}tpInscricaoMunicipal"/>
 *         &lt;element name="NumeroNFe" type="{http://localhost:8080/WsNFe2/tp}tpNumero"/>
 *         &lt;element name="CodigoVerificacao" type="{http://localhost:8080/WsNFe2/tp}tpCodigoVerificacao"/>
 *         &lt;element name="SerieRPS" type="{http://localhost:8080/WsNFe2/tp}tpSerieRPS"/>
 *         &lt;element name="NumeroRPS" type="{http://localhost:8080/WsNFe2/tp}tpNumero"/>
 *         &lt;element name="DataEmissaoRPS" type="{http://localhost:8080/WsNFe2/tp}tpDataHora"/>
 *         &lt;element name="RazaoSocialPrestador" type="{http://localhost:8080/WsNFe2/tp}tpRazaoSocial"/>
 *         &lt;element name="TipoRecolhimento" type="{http://localhost:8080/WsNFe2/tp}tpTipoRecolhimento"/>
 *         &lt;element name="ValorDeduzir" type="{http://localhost:8080/WsNFe2/tp}tpValor" minOccurs="0"/>
 *         &lt;element name="ValorTotal" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
 *         &lt;element name="Aliquota" type="{http://localhost:8080/WsNFe2/tp}tpAliquota"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpConsultaNFSe", propOrder = {
    "inscricaoPrestador",
    "numeroNFe",
    "codigoVerificacao",
    "serieRPS",
    "numeroRPS",
    "dataEmissaoRPS",
    "razaoSocialPrestador",
    "tipoRecolhimento",
    "valorDeduzir",
    "valorTotal",
    "aliquota"
})
public class TpConsultaNFSe {

    @XmlElement(name = "InscricaoPrestador")
    protected long inscricaoPrestador;
    @XmlElement(name = "NumeroNFe")
    protected int numeroNFe;
    @XmlElement(name = "CodigoVerificacao", required = true)
    protected String codigoVerificacao;
    @XmlElement(name = "SerieRPS", required = true)
    protected TpSerieRPS serieRPS;
    @XmlElement(name = "NumeroRPS")
    protected int numeroRPS;
    @XmlElement(name = "DataEmissaoRPS", required = true)
    protected XMLGregorianCalendar dataEmissaoRPS;
    @XmlElement(name = "RazaoSocialPrestador", required = true)
    protected String razaoSocialPrestador;
    @XmlElement(name = "TipoRecolhimento", required = true)
    protected TpTipoRecolhimento tipoRecolhimento;
    @XmlElement(name = "ValorDeduzir")
    protected BigDecimal valorDeduzir;
    @XmlElement(name = "ValorTotal", required = true)
    protected BigDecimal valorTotal;
    @XmlElement(name = "Aliquota", required = true)
    protected BigDecimal aliquota;

    /**
     * Gets the value of the inscricaoPrestador property.
     * 
     */
    public long getInscricaoPrestador() {
        return inscricaoPrestador;
    }

    /**
     * Sets the value of the inscricaoPrestador property.
     * 
     */
    public void setInscricaoPrestador(long value) {
        this.inscricaoPrestador = value;
    }

    /**
     * Gets the value of the numeroNFe property.
     * 
     */
    public int getNumeroNFe() {
        return numeroNFe;
    }

    /**
     * Sets the value of the numeroNFe property.
     * 
     */
    public void setNumeroNFe(int value) {
        this.numeroNFe = value;
    }

    /**
     * Gets the value of the codigoVerificacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoVerificacao() {
        return codigoVerificacao;
    }

    /**
     * Sets the value of the codigoVerificacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoVerificacao(String value) {
        this.codigoVerificacao = value;
    }

    /**
     * Gets the value of the serieRPS property.
     * 
     * @return
     *     possible object is
     *     {@link TpSerieRPS }
     *     
     */
    public TpSerieRPS getSerieRPS() {
        return serieRPS;
    }

    /**
     * Sets the value of the serieRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpSerieRPS }
     *     
     */
    public void setSerieRPS(TpSerieRPS value) {
        this.serieRPS = value;
    }

    /**
     * Gets the value of the numeroRPS property.
     * 
     */
    public int getNumeroRPS() {
        return numeroRPS;
    }

    /**
     * Sets the value of the numeroRPS property.
     * 
     */
    public void setNumeroRPS(int value) {
        this.numeroRPS = value;
    }

    /**
     * Gets the value of the dataEmissaoRPS property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataEmissaoRPS() {
        return dataEmissaoRPS;
    }

    /**
     * Sets the value of the dataEmissaoRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataEmissaoRPS(XMLGregorianCalendar value) {
        this.dataEmissaoRPS = value;
    }

    /**
     * Gets the value of the razaoSocialPrestador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazaoSocialPrestador() {
        return razaoSocialPrestador;
    }

    /**
     * Sets the value of the razaoSocialPrestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazaoSocialPrestador(String value) {
        this.razaoSocialPrestador = value;
    }

    /**
     * Gets the value of the tipoRecolhimento property.
     * 
     * @return
     *     possible object is
     *     {@link TpTipoRecolhimento }
     *     
     */
    public TpTipoRecolhimento getTipoRecolhimento() {
        return tipoRecolhimento;
    }

    /**
     * Sets the value of the tipoRecolhimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpTipoRecolhimento }
     *     
     */
    public void setTipoRecolhimento(TpTipoRecolhimento value) {
        this.tipoRecolhimento = value;
    }

    /**
     * Gets the value of the valorDeduzir property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorDeduzir() {
        return valorDeduzir;
    }

    /**
     * Sets the value of the valorDeduzir property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorDeduzir(BigDecimal value) {
        this.valorDeduzir = value;
    }

    /**
     * Gets the value of the valorTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotal() {
        return valorTotal;
    }

    /**
     * Sets the value of the valorTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotal(BigDecimal value) {
        this.valorTotal = value;
    }

    /**
     * Gets the value of the aliquota property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquota() {
        return aliquota;
    }

    /**
     * Sets the value of the aliquota property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquota(BigDecimal value) {
        this.aliquota = value;
    }

}
