//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 11:09:48 AM BRST 
//


package br.com.tti.sefaz.nfes.schemas.ginfes;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Informações do lote processado.
 * 
 * <p>Java class for tpInformacoesLote complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpInformacoesLote">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroLote" type="{http://localhost:8080/WsNFe2/tp}tpNumero" minOccurs="0"/>
 *         &lt;element name="InscricaoPrestador" type="{http://localhost:8080/WsNFe2/tp}tpInscricaoMunicipal"/>
 *         &lt;element name="CPFCNPJRemetente" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
 *         &lt;element name="DataEnvioLote" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="QtdNotasProcessadas" type="{http://localhost:8080/WsNFe2/tp}tpQuantidade"/>
 *         &lt;element name="TempoProcessamento" type="{http://localhost:8080/WsNFe2/tp}tpTempoProcessamento"/>
 *         &lt;element name="ValorTotalServicos" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
 *         &lt;element name="ValorTotalDeducoes" type="{http://localhost:8080/WsNFe2/tp}tpValor" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpInformacoesLote", propOrder = {
    "numeroLote",
    "inscricaoPrestador",
    "cpfcnpjRemetente",
    "dataEnvioLote",
    "qtdNotasProcessadas",
    "tempoProcessamento",
    "valorTotalServicos",
    "valorTotalDeducoes"
})
public class TpInformacoesLote {

    @XmlElement(name = "NumeroLote")
    protected Integer numeroLote;
    @XmlElement(name = "InscricaoPrestador")
    protected long inscricaoPrestador;
    @XmlElement(name = "CPFCNPJRemetente", required = true)
    protected String cpfcnpjRemetente;
    @XmlElement(name = "DataEnvioLote", required = true)
    protected XMLGregorianCalendar dataEnvioLote;
    @XmlElement(name = "QtdNotasProcessadas", required = true)
    protected BigDecimal qtdNotasProcessadas;
    @XmlElement(name = "TempoProcessamento")
    protected long tempoProcessamento;
    @XmlElement(name = "ValorTotalServicos", required = true)
    protected BigDecimal valorTotalServicos;
    @XmlElement(name = "ValorTotalDeducoes")
    protected BigDecimal valorTotalDeducoes;

    /**
     * Gets the value of the numeroLote property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroLote() {
        return numeroLote;
    }

    /**
     * Sets the value of the numeroLote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroLote(Integer value) {
        this.numeroLote = value;
    }

    /**
     * Gets the value of the inscricaoPrestador property.
     * 
     */
    public long getInscricaoPrestador() {
        return inscricaoPrestador;
    }

    /**
     * Sets the value of the inscricaoPrestador property.
     * 
     */
    public void setInscricaoPrestador(long value) {
        this.inscricaoPrestador = value;
    }

    /**
     * Gets the value of the cpfcnpjRemetente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPFCNPJRemetente() {
        return cpfcnpjRemetente;
    }

    /**
     * Sets the value of the cpfcnpjRemetente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPFCNPJRemetente(String value) {
        this.cpfcnpjRemetente = value;
    }

    /**
     * Gets the value of the dataEnvioLote property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataEnvioLote() {
        return dataEnvioLote;
    }

    /**
     * Sets the value of the dataEnvioLote property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataEnvioLote(XMLGregorianCalendar value) {
        this.dataEnvioLote = value;
    }

    /**
     * Gets the value of the qtdNotasProcessadas property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQtdNotasProcessadas() {
        return qtdNotasProcessadas;
    }

    /**
     * Sets the value of the qtdNotasProcessadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQtdNotasProcessadas(BigDecimal value) {
        this.qtdNotasProcessadas = value;
    }

    /**
     * Gets the value of the tempoProcessamento property.
     * 
     */
    public long getTempoProcessamento() {
        return tempoProcessamento;
    }

    /**
     * Sets the value of the tempoProcessamento property.
     * 
     */
    public void setTempoProcessamento(long value) {
        this.tempoProcessamento = value;
    }

    /**
     * Gets the value of the valorTotalServicos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalServicos() {
        return valorTotalServicos;
    }

    /**
     * Sets the value of the valorTotalServicos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalServicos(BigDecimal value) {
        this.valorTotalServicos = value;
    }

    /**
     * Gets the value of the valorTotalDeducoes property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalDeducoes() {
        return valorTotalDeducoes;
    }

    /**
     * Sets the value of the valorTotalDeducoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalDeducoes(BigDecimal value) {
        this.valorTotalDeducoes = value;
    }

}
