//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 11:09:48 AM BRST 
//


package br.com.tti.sefaz.nfes.schemas.ginfes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Lista de Detalhes da Consulta de NFSe.
 * 
 * <p>Java class for tpLoteConsultaNFSe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpLoteConsultaNFSe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NotaConsulta" type="{http://localhost:8080/WsNFe2/tp}tpNotasConsultaNFSe" minOccurs="0"/>
 *         &lt;element name="RPSConsulta" type="{http://localhost:8080/WsNFe2/tp}tpRPSsConsultaNFSe" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpLoteConsultaNFSe", propOrder = {
    "notaConsulta",
    "rpsConsulta"
})
public class TpLoteConsultaNFSe {

    @XmlElement(name = "NotaConsulta")
    protected TpNotasConsultaNFSe notaConsulta;
    @XmlElement(name = "RPSConsulta")
    protected TpRPSsConsultaNFSe rpsConsulta;
    @XmlAttribute(name = "Id")
    protected String id;

    /**
     * Gets the value of the notaConsulta property.
     * 
     * @return
     *     possible object is
     *     {@link TpNotasConsultaNFSe }
     *     
     */
    public TpNotasConsultaNFSe getNotaConsulta() {
        return notaConsulta;
    }

    /**
     * Sets the value of the notaConsulta property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpNotasConsultaNFSe }
     *     
     */
    public void setNotaConsulta(TpNotasConsultaNFSe value) {
        this.notaConsulta = value;
    }

    /**
     * Gets the value of the rpsConsulta property.
     * 
     * @return
     *     possible object is
     *     {@link TpRPSsConsultaNFSe }
     *     
     */
    public TpRPSsConsultaNFSe getRPSConsulta() {
        return rpsConsulta;
    }

    /**
     * Sets the value of the rpsConsulta property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpRPSsConsultaNFSe }
     *     
     */
    public void setRPSConsulta(TpRPSsConsultaNFSe value) {
        this.rpsConsulta = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
