//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 11:09:48 AM BRST 
//


package br.com.tti.sefaz.nfes.schemas.ginfes;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Tipo que representa um RPS.
 * 
 * <p>Java class for tpRPS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpRPS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Assinatura" type="{http://localhost:8080/WsNFe2/tp}tpAssinatura"/>
 *         &lt;element name="InscricaoMunicipalPrestador" type="{http://localhost:8080/WsNFe2/tp}tpInscricaoMunicipal"/>
 *         &lt;element name="RazaoSocialPrestador" type="{http://localhost:8080/WsNFe2/tp}tpRazaoSocialPrestador"/>
 *         &lt;element name="TipoRPS" type="{http://localhost:8080/WsNFe2/tp}tpTipoRPS"/>
 *         &lt;element name="SerieRPS" type="{http://localhost:8080/WsNFe2/tp}tpSerieRPS"/>
 *         &lt;element name="NumeroRPS" type="{http://localhost:8080/WsNFe2/tp}tpNumero"/>
 *         &lt;element name="DataEmissaoRPS" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="SituacaoRPS" type="{http://localhost:8080/WsNFe2/tp}tpSituacaoRPS"/>
 *         &lt;element name="SerieRPSSubstituido" type="{http://localhost:8080/WsNFe2/tp}tpSerieRPSSubstituido" minOccurs="0"/>
 *         &lt;element name="NumeroRPSSubstituido" type="{http://localhost:8080/WsNFe2/tp}tpNumeroComZero" minOccurs="0"/>
 *         &lt;element name="NumeroNFSeSubstituida" type="{http://localhost:8080/WsNFe2/tp}tpNumeroComZero" minOccurs="0"/>
 *         &lt;element name="DataEmissaoNFSeSubstituida" type="{http://localhost:8080/WsNFe2/tp}tpDataNulo" minOccurs="0"/>
 *         &lt;element name="SeriePrestacao" type="{http://localhost:8080/WsNFe2/tp}tpSeriePrestacao"/>
 *         &lt;element name="InscricaoMunicipalTomador" type="{http://localhost:8080/WsNFe2/tp}tpInscricaoMunicipalNulo"/>
 *         &lt;element name="CPFCNPJTomador" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJ"/>
 *         &lt;element name="RazaoSocialTomador" type="{http://localhost:8080/WsNFe2/tp}tpRazaoSocial"/>
 *         &lt;element name="DocTomadorEstrangeiro" type="{http://localhost:8080/WsNFe2/tp}tpDocTomadorEstrangeiro" minOccurs="0"/>
 *         &lt;element name="TipoLogradouroTomador" type="{http://localhost:8080/WsNFe2/tp}tpTipoLogradouro"/>
 *         &lt;element name="LogradouroTomador" type="{http://localhost:8080/WsNFe2/tp}tpLogradouro"/>
 *         &lt;element name="NumeroEnderecoTomador" type="{http://localhost:8080/WsNFe2/tp}tpNumeroEndereco"/>
 *         &lt;element name="ComplementoEnderecoTomador" type="{http://localhost:8080/WsNFe2/tp}tpComplementoEndereco" minOccurs="0"/>
 *         &lt;element name="TipoBairroTomador" type="{http://localhost:8080/WsNFe2/tp}tpTipoBairro"/>
 *         &lt;element name="BairroTomador" type="{http://localhost:8080/WsNFe2/tp}tpBairro"/>
 *         &lt;element name="CidadeTomador" type="{http://localhost:8080/WsNFe2/tp}tpCodCidade"/>
 *         &lt;element name="CidadeTomadorDescricao" type="{http://localhost:8080/WsNFe2/tp}tpCidadeTomadorDescricao"/>
 *         &lt;element name="CEPTomador" type="{http://localhost:8080/WsNFe2/tp}tpCEP"/>
 *         &lt;element name="EmailTomador" type="{http://localhost:8080/WsNFe2/tp}tpEmail"/>
 *         &lt;element name="CodigoAtividade" type="{http://localhost:8080/WsNFe2/tp}tpCodigoAtividade"/>
 *         &lt;element name="AliquotaAtividade" type="{http://localhost:8080/WsNFe2/tp}tpAliquota"/>
 *         &lt;element name="TipoRecolhimento" type="{http://localhost:8080/WsNFe2/tp}tpTipoRecolhimento"/>
 *         &lt;element name="MunicipioPrestacao" type="{http://localhost:8080/WsNFe2/tp}tpCodCidade"/>
 *         &lt;element name="MunicipioPrestacaoDescricao" type="{http://localhost:8080/WsNFe2/tp}tpCidadeDescricao"/>
 *         &lt;element name="Operacao" type="{http://localhost:8080/WsNFe2/tp}tpOperacao"/>
 *         &lt;element name="Tributacao" type="{http://localhost:8080/WsNFe2/tp}tpTributacao"/>
 *         &lt;element name="ValorPIS" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
 *         &lt;element name="ValorCOFINS" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
 *         &lt;element name="ValorINSS" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
 *         &lt;element name="ValorIR" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
 *         &lt;element name="ValorCSLL" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
 *         &lt;element name="AliquotaPIS" type="{http://localhost:8080/WsNFe2/tp}tpAliquota"/>
 *         &lt;element name="AliquotaCOFINS" type="{http://localhost:8080/WsNFe2/tp}tpAliquota"/>
 *         &lt;element name="AliquotaINSS" type="{http://localhost:8080/WsNFe2/tp}tpAliquota"/>
 *         &lt;element name="AliquotaIR" type="{http://localhost:8080/WsNFe2/tp}tpAliquota"/>
 *         &lt;element name="AliquotaCSLL" type="{http://localhost:8080/WsNFe2/tp}tpAliquota"/>
 *         &lt;element name="DescricaoRPS" type="{http://localhost:8080/WsNFe2/tp}tpDescricaoRPS"/>
 *         &lt;element name="DDDPrestador" type="{http://localhost:8080/WsNFe2/tp}tpDDDNulo"/>
 *         &lt;element name="TelefonePrestador" type="{http://localhost:8080/WsNFe2/tp}tpFoneNulo"/>
 *         &lt;element name="DDDTomador" type="{http://localhost:8080/WsNFe2/tp}tpDDDNulo"/>
 *         &lt;element name="TelefoneTomador" type="{http://localhost:8080/WsNFe2/tp}tpFoneNulo"/>
 *         &lt;element name="MotCancelamento" type="{http://localhost:8080/WsNFe2/tp}tpMotCancelamento" minOccurs="0"/>
 *         &lt;element name="CPFCNPJIntermediario" type="{http://localhost:8080/WsNFe2/tp}tpCPFCNPJnulo" minOccurs="0"/>
 *         &lt;element name="Deducoes" type="{http://localhost:8080/WsNFe2/tp}tpListaDeducoes" minOccurs="0"/>
 *         &lt;element name="Itens" type="{http://localhost:8080/WsNFe2/tp}tpListaItens"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpRPS", propOrder = {
    "assinatura",
    "inscricaoMunicipalPrestador",
    "razaoSocialPrestador",
    "tipoRPS",
    "serieRPS",
    "numeroRPS",
    "dataEmissaoRPS",
    "situacaoRPS",
    "serieRPSSubstituido",
    "numeroRPSSubstituido",
    "numeroNFSeSubstituida",
    "dataEmissaoNFSeSubstituida",
    "seriePrestacao",
    "inscricaoMunicipalTomador",
    "cpfcnpjTomador",
    "razaoSocialTomador",
    "docTomadorEstrangeiro",
    "tipoLogradouroTomador",
    "logradouroTomador",
    "numeroEnderecoTomador",
    "complementoEnderecoTomador",
    "tipoBairroTomador",
    "bairroTomador",
    "cidadeTomador",
    "cidadeTomadorDescricao",
    "cepTomador",
    "emailTomador",
    "codigoAtividade",
    "aliquotaAtividade",
    "tipoRecolhimento",
    "municipioPrestacao",
    "municipioPrestacaoDescricao",
    "operacao",
    "tributacao",
    "valorPIS",
    "valorCOFINS",
    "valorINSS",
    "valorIR",
    "valorCSLL",
    "aliquotaPIS",
    "aliquotaCOFINS",
    "aliquotaINSS",
    "aliquotaIR",
    "aliquotaCSLL",
    "descricaoRPS",
    "dddPrestador",
    "telefonePrestador",
    "dddTomador",
    "telefoneTomador",
    "motCancelamento",
    "cpfcnpjIntermediario",
    "deducoes",
    "itens"
})
public class TpRPS {

    @XmlElement(name = "Assinatura", required = true)
    protected byte[] assinatura;
    @XmlElement(name = "InscricaoMunicipalPrestador")
    protected long inscricaoMunicipalPrestador;
    @XmlElement(name = "RazaoSocialPrestador", required = true)
    protected String razaoSocialPrestador;
    @XmlElement(name = "TipoRPS", required = true)
    protected TpTipoRPS tipoRPS;
    @XmlElement(name = "SerieRPS", required = true)
    protected TpSerieRPS serieRPS;
    @XmlElement(name = "NumeroRPS")
    protected int numeroRPS;
    @XmlElement(name = "DataEmissaoRPS", required = true)
    protected XMLGregorianCalendar dataEmissaoRPS;
    @XmlElement(name = "SituacaoRPS", required = true)
    protected TpSituacaoRPS situacaoRPS;
    @XmlElement(name = "SerieRPSSubstituido")
    protected String serieRPSSubstituido;
    @XmlElement(name = "NumeroRPSSubstituido")
    protected Integer numeroRPSSubstituido;
    @XmlElement(name = "NumeroNFSeSubstituida")
    protected Integer numeroNFSeSubstituida;
    @XmlElement(name = "DataEmissaoNFSeSubstituida")
    protected String dataEmissaoNFSeSubstituida;
    @XmlElement(name = "SeriePrestacao")
    protected byte seriePrestacao;
    @XmlElement(name = "InscricaoMunicipalTomador", required = true)
    protected String inscricaoMunicipalTomador;
    @XmlElement(name = "CPFCNPJTomador", required = true)
    protected String cpfcnpjTomador;
    @XmlElement(name = "RazaoSocialTomador", required = true)
    protected String razaoSocialTomador;
    @XmlElement(name = "DocTomadorEstrangeiro")
    protected String docTomadorEstrangeiro;
    @XmlElement(name = "TipoLogradouroTomador", required = true)
    protected String tipoLogradouroTomador;
    @XmlElement(name = "LogradouroTomador", required = true)
    protected String logradouroTomador;
    @XmlElement(name = "NumeroEnderecoTomador", required = true)
    protected String numeroEnderecoTomador;
    @XmlElement(name = "ComplementoEnderecoTomador")
    protected String complementoEnderecoTomador;
    @XmlElement(name = "TipoBairroTomador", required = true)
    protected String tipoBairroTomador;
    @XmlElement(name = "BairroTomador", required = true)
    protected String bairroTomador;
    @XmlElement(name = "CidadeTomador")
    protected long cidadeTomador;
    @XmlElement(name = "CidadeTomadorDescricao", required = true)
    protected String cidadeTomadorDescricao;
    @XmlElement(name = "CEPTomador")
    protected int cepTomador;
    @XmlElement(name = "EmailTomador", required = true)
    protected String emailTomador;
    @XmlElement(name = "CodigoAtividade")
    protected int codigoAtividade;
    @XmlElement(name = "AliquotaAtividade", required = true)
    protected BigDecimal aliquotaAtividade;
    @XmlElement(name = "TipoRecolhimento", required = true)
    protected TpTipoRecolhimento tipoRecolhimento;
    @XmlElement(name = "MunicipioPrestacao")
    protected long municipioPrestacao;
    @XmlElement(name = "MunicipioPrestacaoDescricao", required = true)
    protected String municipioPrestacaoDescricao;
    @XmlElement(name = "Operacao", required = true)
    protected TpOperacao operacao;
    @XmlElement(name = "Tributacao", required = true)
    protected TpTributacao tributacao;
    @XmlElement(name = "ValorPIS", required = true)
    protected BigDecimal valorPIS;
    @XmlElement(name = "ValorCOFINS", required = true)
    protected BigDecimal valorCOFINS;
    @XmlElement(name = "ValorINSS", required = true)
    protected BigDecimal valorINSS;
    @XmlElement(name = "ValorIR", required = true)
    protected BigDecimal valorIR;
    @XmlElement(name = "ValorCSLL", required = true)
    protected BigDecimal valorCSLL;
    @XmlElement(name = "AliquotaPIS", required = true)
    protected BigDecimal aliquotaPIS;
    @XmlElement(name = "AliquotaCOFINS", required = true)
    protected BigDecimal aliquotaCOFINS;
    @XmlElement(name = "AliquotaINSS", required = true)
    protected BigDecimal aliquotaINSS;
    @XmlElement(name = "AliquotaIR", required = true)
    protected BigDecimal aliquotaIR;
    @XmlElement(name = "AliquotaCSLL", required = true)
    protected BigDecimal aliquotaCSLL;
    @XmlElement(name = "DescricaoRPS", required = true)
    protected String descricaoRPS;
    @XmlElement(name = "DDDPrestador", required = true)
    protected String dddPrestador;
    @XmlList
    @XmlElement(name = "TelefonePrestador", required = true)
    protected List<String> telefonePrestador;
    @XmlElement(name = "DDDTomador", required = true)
    protected String dddTomador;
    @XmlList
    @XmlElement(name = "TelefoneTomador", required = true)
    protected List<String> telefoneTomador;
    @XmlElement(name = "MotCancelamento")
    protected String motCancelamento;
    @XmlElement(name = "CPFCNPJIntermediario")
    protected String cpfcnpjIntermediario;
    @XmlElement(name = "Deducoes")
    protected TpListaDeducoes deducoes;
    @XmlElement(name = "Itens", required = true)
    protected TpListaItens itens;
    @XmlAttribute(name = "Id")
    protected String id;

    /**
     * Gets the value of the assinatura property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getAssinatura() {
        return assinatura;
    }

    /**
     * Sets the value of the assinatura property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setAssinatura(byte[] value) {
        this.assinatura = ((byte[]) value);
    }

    /**
     * Gets the value of the inscricaoMunicipalPrestador property.
     * 
     */
    public long getInscricaoMunicipalPrestador() {
        return inscricaoMunicipalPrestador;
    }

    /**
     * Sets the value of the inscricaoMunicipalPrestador property.
     * 
     */
    public void setInscricaoMunicipalPrestador(long value) {
        this.inscricaoMunicipalPrestador = value;
    }

    /**
     * Gets the value of the razaoSocialPrestador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazaoSocialPrestador() {
        return razaoSocialPrestador;
    }

    /**
     * Sets the value of the razaoSocialPrestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazaoSocialPrestador(String value) {
        this.razaoSocialPrestador = value;
    }

    /**
     * Gets the value of the tipoRPS property.
     * 
     * @return
     *     possible object is
     *     {@link TpTipoRPS }
     *     
     */
    public TpTipoRPS getTipoRPS() {
        return tipoRPS;
    }

    /**
     * Sets the value of the tipoRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpTipoRPS }
     *     
     */
    public void setTipoRPS(TpTipoRPS value) {
        this.tipoRPS = value;
    }

    /**
     * Gets the value of the serieRPS property.
     * 
     * @return
     *     possible object is
     *     {@link TpSerieRPS }
     *     
     */
    public TpSerieRPS getSerieRPS() {
        return serieRPS;
    }

    /**
     * Sets the value of the serieRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpSerieRPS }
     *     
     */
    public void setSerieRPS(TpSerieRPS value) {
        this.serieRPS = value;
    }

    /**
     * Gets the value of the numeroRPS property.
     * 
     */
    public int getNumeroRPS() {
        return numeroRPS;
    }

    /**
     * Sets the value of the numeroRPS property.
     * 
     */
    public void setNumeroRPS(int value) {
        this.numeroRPS = value;
    }

    /**
     * Gets the value of the dataEmissaoRPS property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataEmissaoRPS() {
        return dataEmissaoRPS;
    }

    /**
     * Sets the value of the dataEmissaoRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataEmissaoRPS(XMLGregorianCalendar value) {
        this.dataEmissaoRPS = value;
    }

    /**
     * Gets the value of the situacaoRPS property.
     * 
     * @return
     *     possible object is
     *     {@link TpSituacaoRPS }
     *     
     */
    public TpSituacaoRPS getSituacaoRPS() {
        return situacaoRPS;
    }

    /**
     * Sets the value of the situacaoRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpSituacaoRPS }
     *     
     */
    public void setSituacaoRPS(TpSituacaoRPS value) {
        this.situacaoRPS = value;
    }

    /**
     * Gets the value of the serieRPSSubstituido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerieRPSSubstituido() {
        return serieRPSSubstituido;
    }

    /**
     * Sets the value of the serieRPSSubstituido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerieRPSSubstituido(String value) {
        this.serieRPSSubstituido = value;
    }

    /**
     * Gets the value of the numeroRPSSubstituido property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroRPSSubstituido() {
        return numeroRPSSubstituido;
    }

    /**
     * Sets the value of the numeroRPSSubstituido property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroRPSSubstituido(Integer value) {
        this.numeroRPSSubstituido = value;
    }

    /**
     * Gets the value of the numeroNFSeSubstituida property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroNFSeSubstituida() {
        return numeroNFSeSubstituida;
    }

    /**
     * Sets the value of the numeroNFSeSubstituida property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroNFSeSubstituida(Integer value) {
        this.numeroNFSeSubstituida = value;
    }

    /**
     * Gets the value of the dataEmissaoNFSeSubstituida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataEmissaoNFSeSubstituida() {
        return dataEmissaoNFSeSubstituida;
    }

    /**
     * Sets the value of the dataEmissaoNFSeSubstituida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataEmissaoNFSeSubstituida(String value) {
        this.dataEmissaoNFSeSubstituida = value;
    }

    /**
     * Gets the value of the seriePrestacao property.
     * 
     */
    public byte getSeriePrestacao() {
        return seriePrestacao;
    }

    /**
     * Sets the value of the seriePrestacao property.
     * 
     */
    public void setSeriePrestacao(byte value) {
        this.seriePrestacao = value;
    }

    /**
     * Gets the value of the inscricaoMunicipalTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInscricaoMunicipalTomador() {
        return inscricaoMunicipalTomador;
    }

    /**
     * Sets the value of the inscricaoMunicipalTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInscricaoMunicipalTomador(String value) {
        this.inscricaoMunicipalTomador = value;
    }

    /**
     * Gets the value of the cpfcnpjTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPFCNPJTomador() {
        return cpfcnpjTomador;
    }

    /**
     * Sets the value of the cpfcnpjTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPFCNPJTomador(String value) {
        this.cpfcnpjTomador = value;
    }

    /**
     * Gets the value of the razaoSocialTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazaoSocialTomador() {
        return razaoSocialTomador;
    }

    /**
     * Sets the value of the razaoSocialTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazaoSocialTomador(String value) {
        this.razaoSocialTomador = value;
    }

    /**
     * Gets the value of the docTomadorEstrangeiro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocTomadorEstrangeiro() {
        return docTomadorEstrangeiro;
    }

    /**
     * Sets the value of the docTomadorEstrangeiro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocTomadorEstrangeiro(String value) {
        this.docTomadorEstrangeiro = value;
    }

    /**
     * Gets the value of the tipoLogradouroTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoLogradouroTomador() {
        return tipoLogradouroTomador;
    }

    /**
     * Sets the value of the tipoLogradouroTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoLogradouroTomador(String value) {
        this.tipoLogradouroTomador = value;
    }

    /**
     * Gets the value of the logradouroTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogradouroTomador() {
        return logradouroTomador;
    }

    /**
     * Sets the value of the logradouroTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogradouroTomador(String value) {
        this.logradouroTomador = value;
    }

    /**
     * Gets the value of the numeroEnderecoTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroEnderecoTomador() {
        return numeroEnderecoTomador;
    }

    /**
     * Sets the value of the numeroEnderecoTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroEnderecoTomador(String value) {
        this.numeroEnderecoTomador = value;
    }

    /**
     * Gets the value of the complementoEnderecoTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplementoEnderecoTomador() {
        return complementoEnderecoTomador;
    }

    /**
     * Sets the value of the complementoEnderecoTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplementoEnderecoTomador(String value) {
        this.complementoEnderecoTomador = value;
    }

    /**
     * Gets the value of the tipoBairroTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoBairroTomador() {
        return tipoBairroTomador;
    }

    /**
     * Sets the value of the tipoBairroTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoBairroTomador(String value) {
        this.tipoBairroTomador = value;
    }

    /**
     * Gets the value of the bairroTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBairroTomador() {
        return bairroTomador;
    }

    /**
     * Sets the value of the bairroTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBairroTomador(String value) {
        this.bairroTomador = value;
    }

    /**
     * Gets the value of the cidadeTomador property.
     * 
     */
    public long getCidadeTomador() {
        return cidadeTomador;
    }

    /**
     * Sets the value of the cidadeTomador property.
     * 
     */
    public void setCidadeTomador(long value) {
        this.cidadeTomador = value;
    }

    /**
     * Gets the value of the cidadeTomadorDescricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCidadeTomadorDescricao() {
        return cidadeTomadorDescricao;
    }

    /**
     * Sets the value of the cidadeTomadorDescricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCidadeTomadorDescricao(String value) {
        this.cidadeTomadorDescricao = value;
    }

    /**
     * Gets the value of the cepTomador property.
     * 
     */
    public int getCEPTomador() {
        return cepTomador;
    }

    /**
     * Sets the value of the cepTomador property.
     * 
     */
    public void setCEPTomador(int value) {
        this.cepTomador = value;
    }

    /**
     * Gets the value of the emailTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailTomador() {
        return emailTomador;
    }

    /**
     * Sets the value of the emailTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailTomador(String value) {
        this.emailTomador = value;
    }

    /**
     * Gets the value of the codigoAtividade property.
     * 
     */
    public int getCodigoAtividade() {
        return codigoAtividade;
    }

    /**
     * Sets the value of the codigoAtividade property.
     * 
     */
    public void setCodigoAtividade(int value) {
        this.codigoAtividade = value;
    }

    /**
     * Gets the value of the aliquotaAtividade property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquotaAtividade() {
        return aliquotaAtividade;
    }

    /**
     * Sets the value of the aliquotaAtividade property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquotaAtividade(BigDecimal value) {
        this.aliquotaAtividade = value;
    }

    /**
     * Gets the value of the tipoRecolhimento property.
     * 
     * @return
     *     possible object is
     *     {@link TpTipoRecolhimento }
     *     
     */
    public TpTipoRecolhimento getTipoRecolhimento() {
        return tipoRecolhimento;
    }

    /**
     * Sets the value of the tipoRecolhimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpTipoRecolhimento }
     *     
     */
    public void setTipoRecolhimento(TpTipoRecolhimento value) {
        this.tipoRecolhimento = value;
    }

    /**
     * Gets the value of the municipioPrestacao property.
     * 
     */
    public long getMunicipioPrestacao() {
        return municipioPrestacao;
    }

    /**
     * Sets the value of the municipioPrestacao property.
     * 
     */
    public void setMunicipioPrestacao(long value) {
        this.municipioPrestacao = value;
    }

    /**
     * Gets the value of the municipioPrestacaoDescricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipioPrestacaoDescricao() {
        return municipioPrestacaoDescricao;
    }

    /**
     * Sets the value of the municipioPrestacaoDescricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipioPrestacaoDescricao(String value) {
        this.municipioPrestacaoDescricao = value;
    }

    /**
     * Gets the value of the operacao property.
     * 
     * @return
     *     possible object is
     *     {@link TpOperacao }
     *     
     */
    public TpOperacao getOperacao() {
        return operacao;
    }

    /**
     * Sets the value of the operacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpOperacao }
     *     
     */
    public void setOperacao(TpOperacao value) {
        this.operacao = value;
    }

    /**
     * Gets the value of the tributacao property.
     * 
     * @return
     *     possible object is
     *     {@link TpTributacao }
     *     
     */
    public TpTributacao getTributacao() {
        return tributacao;
    }

    /**
     * Sets the value of the tributacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpTributacao }
     *     
     */
    public void setTributacao(TpTributacao value) {
        this.tributacao = value;
    }

    /**
     * Gets the value of the valorPIS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorPIS() {
        return valorPIS;
    }

    /**
     * Sets the value of the valorPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorPIS(BigDecimal value) {
        this.valorPIS = value;
    }

    /**
     * Gets the value of the valorCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorCOFINS() {
        return valorCOFINS;
    }

    /**
     * Sets the value of the valorCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorCOFINS(BigDecimal value) {
        this.valorCOFINS = value;
    }

    /**
     * Gets the value of the valorINSS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorINSS() {
        return valorINSS;
    }

    /**
     * Sets the value of the valorINSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorINSS(BigDecimal value) {
        this.valorINSS = value;
    }

    /**
     * Gets the value of the valorIR property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorIR() {
        return valorIR;
    }

    /**
     * Sets the value of the valorIR property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorIR(BigDecimal value) {
        this.valorIR = value;
    }

    /**
     * Gets the value of the valorCSLL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorCSLL() {
        return valorCSLL;
    }

    /**
     * Sets the value of the valorCSLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorCSLL(BigDecimal value) {
        this.valorCSLL = value;
    }

    /**
     * Gets the value of the aliquotaPIS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquotaPIS() {
        return aliquotaPIS;
    }

    /**
     * Sets the value of the aliquotaPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquotaPIS(BigDecimal value) {
        this.aliquotaPIS = value;
    }

    /**
     * Gets the value of the aliquotaCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquotaCOFINS() {
        return aliquotaCOFINS;
    }

    /**
     * Sets the value of the aliquotaCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquotaCOFINS(BigDecimal value) {
        this.aliquotaCOFINS = value;
    }

    /**
     * Gets the value of the aliquotaINSS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquotaINSS() {
        return aliquotaINSS;
    }

    /**
     * Sets the value of the aliquotaINSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquotaINSS(BigDecimal value) {
        this.aliquotaINSS = value;
    }

    /**
     * Gets the value of the aliquotaIR property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquotaIR() {
        return aliquotaIR;
    }

    /**
     * Sets the value of the aliquotaIR property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquotaIR(BigDecimal value) {
        this.aliquotaIR = value;
    }

    /**
     * Gets the value of the aliquotaCSLL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquotaCSLL() {
        return aliquotaCSLL;
    }

    /**
     * Sets the value of the aliquotaCSLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquotaCSLL(BigDecimal value) {
        this.aliquotaCSLL = value;
    }

    /**
     * Gets the value of the descricaoRPS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricaoRPS() {
        return descricaoRPS;
    }

    /**
     * Sets the value of the descricaoRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricaoRPS(String value) {
        this.descricaoRPS = value;
    }

    /**
     * Gets the value of the dddPrestador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDDPrestador() {
        return dddPrestador;
    }

    /**
     * Sets the value of the dddPrestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDDPrestador(String value) {
        this.dddPrestador = value;
    }

    /**
     * Gets the value of the telefonePrestador property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telefonePrestador property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelefonePrestador().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTelefonePrestador() {
        if (telefonePrestador == null) {
            telefonePrestador = new ArrayList<String>();
        }
        return this.telefonePrestador;
    }

    /**
     * Gets the value of the dddTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDDTomador() {
        return dddTomador;
    }

    /**
     * Sets the value of the dddTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDDTomador(String value) {
        this.dddTomador = value;
    }

    /**
     * Gets the value of the telefoneTomador property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telefoneTomador property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelefoneTomador().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTelefoneTomador() {
        if (telefoneTomador == null) {
            telefoneTomador = new ArrayList<String>();
        }
        return this.telefoneTomador;
    }

    /**
     * Gets the value of the motCancelamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotCancelamento() {
        return motCancelamento;
    }

    /**
     * Sets the value of the motCancelamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotCancelamento(String value) {
        this.motCancelamento = value;
    }

    /**
     * Gets the value of the cpfcnpjIntermediario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPFCNPJIntermediario() {
        return cpfcnpjIntermediario;
    }

    /**
     * Sets the value of the cpfcnpjIntermediario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPFCNPJIntermediario(String value) {
        this.cpfcnpjIntermediario = value;
    }

    /**
     * Gets the value of the deducoes property.
     * 
     * @return
     *     possible object is
     *     {@link TpListaDeducoes }
     *     
     */
    public TpListaDeducoes getDeducoes() {
        return deducoes;
    }

    /**
     * Sets the value of the deducoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpListaDeducoes }
     *     
     */
    public void setDeducoes(TpListaDeducoes value) {
        this.deducoes = value;
    }

    /**
     * Gets the value of the itens property.
     * 
     * @return
     *     possible object is
     *     {@link TpListaItens }
     *     
     */
    public TpListaItens getItens() {
        return itens;
    }

    /**
     * Sets the value of the itens property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpListaItens }
     *     
     */
    public void setItens(TpListaItens value) {
        this.itens = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
