//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.03 at 02:45:07 PM BRT 
//

package br.com.tti.sefaz.systemconfig.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for configuracaoSistema complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;configuracaoSistema&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;urlBancoDados&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;usuario&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;password&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;modoOperacao&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;diretorioArquivos&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configuracaoSistema", propOrder = { "urlBancoDados", "driver",
		"usuario", "password", "connectorClass", "diretorioArquivos",
		"pfxDeTransmissao", "trustStore", "arquivoServicos" })
public class ConfiguracaoSistema {

	protected String urlBancoDados;
	protected String driver;
	protected String usuario;
	protected String password;
	protected String connectorClass;
	protected String diretorioArquivos;
	protected String pfxDeTransmissao;
	protected String trustStore;
	protected String arquivoServicos;

	/**
	 * Gets the value of the urlBancoDados property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrlBancoDados() {
		return urlBancoDados;
	}

	/**
	 * Sets the value of the urlBancoDados property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUrlBancoDados(String value) {
		this.urlBancoDados = value;
	}

	/**
	 * Gets the value of the usuario property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUsuario() {
		return usuario;
	}

	/**
	 * Sets the value of the usuario property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUsuario(String value) {
		this.usuario = value;
	}

	/**
	 * Gets the value of the password property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * Sets the value of the password property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPassword(String value) {
		this.password = value;
	}

	/**
	 * Gets the value of the diretorioArquivos property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDiretorioArquivos() {
		return diretorioArquivos;
	}

	/**
	 * Sets the value of the diretorioArquivos property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDiretorioArquivos(String value) {
		this.diretorioArquivos = value;
	}

	public String getPfxDeTransmissao() {
		return pfxDeTransmissao;
	}

	public void setPfxDeTransmissao(String pfxDeTransmissao) {
		this.pfxDeTransmissao = pfxDeTransmissao;
	}

	public String getTrustStore() {
		return trustStore;
	}

	public void setTrustStore(String trustStore) {
		this.trustStore = trustStore;
	}

	public String getConnectorClass() {
		return connectorClass;
	}

	public void setConnectorClass(String connectorClass) {
		this.connectorClass = connectorClass;
	}

	public String getArquivoServicos() {
		return arquivoServicos;
	}

	public void setArquivoServicos(String arquivoServicos) {
		this.arquivoServicos = arquivoServicos;
	}

	public String getDriver() {
		return driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

}