//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.03 at 02:45:07 PM BRT 
//


package br.com.tti.sefaz.systemconfig.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entrada complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entrada">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nomeEsquema" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="versaoEsquema" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entrada", propOrder = {
    "nomeEsquema",
    "versaoEsquema"
})
public class Entrada {

    protected String nomeEsquema;
    protected String versaoEsquema;

    /**
     * Gets the value of the nomeEsquema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeEsquema() {
        return nomeEsquema;
    }

    /**
     * Sets the value of the nomeEsquema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeEsquema(String value) {
        this.nomeEsquema = value;
    }

    /**
     * Gets the value of the versaoEsquema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersaoEsquema() {
        return versaoEsquema;
    }

    /**
     * Sets the value of the versaoEsquema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersaoEsquema(String value) {
        this.versaoEsquema = value;
    }

}
