//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.28 at 12:24:37 PM BRT 
//


package br.com.tti.sefaz.sender.xml.schema;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.taragona.nfe.util.xml.teste package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NFeServicos_QNAME = new QName("", "nFeServicos");
    private final static QName _ConfiguracaoServico_QNAME = new QName("", "configuracaoServico");
    private final static QName _NFeServico_QNAME = new QName("", "nFeServico");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.taragona.nfe.util.xml.teste
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfiguracaoServico }
     * 
     */
    public ConfiguracaoServico createConfiguracaoServico() {
        return new ConfiguracaoServico();
    }

    /**
     * Create an instance of {@link NFeServicos }
     * 
     */
    public NFeServicos createNFeServicos() {
        return new NFeServicos();
    }

    /**
     * Create an instance of {@link NFeServico }
     * 
     */
    public NFeServico createNFeServico() {
        return new NFeServico();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NFeServicos }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nFeServicos")
    public JAXBElement<NFeServicos> createNFeServicos(NFeServicos value) {
        return new JAXBElement<NFeServicos>(_NFeServicos_QNAME, NFeServicos.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfiguracaoServico }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "configuracaoServico")
    public JAXBElement<ConfiguracaoServico> createConfiguracaoServico(ConfiguracaoServico value) {
        return new JAXBElement<ConfiguracaoServico>(_ConfiguracaoServico_QNAME, ConfiguracaoServico.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NFeServico }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nFeServico")
    public JAXBElement<NFeServico> createNFeServico(NFeServico value) {
        return new JAXBElement<NFeServico>(_NFeServico_QNAME, NFeServico.class, null, value);
    }

}
