//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.28 at 09:44:11 AM BRST 
//


package br.org.abrasf.nfse.semfazonline.esquemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcDadosIntermediario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcDadosIntermediario">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentificacaoIntermediario" type="{http://www.abrasf.org.br/nfse.xsd}tcIdentificacaoIntermediario"/>
 *         &lt;element name="RazaoSocial" type="{http://www.abrasf.org.br/nfse.xsd}tsRazaoSocial"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcDadosIntermediario", propOrder = {
    "identificacaoIntermediario",
    "razaoSocial"
})
public class TcDadosIntermediario {

    @XmlElement(name = "IdentificacaoIntermediario", required = true)
    protected TcIdentificacaoIntermediario identificacaoIntermediario;
    @XmlElement(name = "RazaoSocial", required = true)
    protected String razaoSocial;

    /**
     * Gets the value of the identificacaoIntermediario property.
     * 
     * @return
     *     possible object is
     *     {@link TcIdentificacaoIntermediario }
     *     
     */
    public TcIdentificacaoIntermediario getIdentificacaoIntermediario() {
        return identificacaoIntermediario;
    }

    /**
     * Sets the value of the identificacaoIntermediario property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoIntermediario }
     *     
     */
    public void setIdentificacaoIntermediario(TcIdentificacaoIntermediario value) {
        this.identificacaoIntermediario = value;
    }

    /**
     * Gets the value of the razaoSocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazaoSocial() {
        return razaoSocial;
    }

    /**
     * Sets the value of the razaoSocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazaoSocial(String value) {
        this.razaoSocial = value;
    }

}
