//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 03:50:08 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.prefeitura.sp.gov.br/nfe/tipos")
package br.com.tti.sefaz.nfes.schemas.saopaulo.retornoconsulta;
