//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 03:50:08 PM BRT 
//

package br.com.tti.sefaz.nfes.schemas.saopaulo.retornoconsulta;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cabecalho">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Sucesso" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpSucesso"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Versao" use="required" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpVersao" fixed="1" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Alerta" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpEvento" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Erro" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpEvento" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NFe" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpNFe" maxOccurs="50" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "cabecalho", "alerta", "erro", "nFe" })
@XmlRootElement(name = "RetornoConsulta", namespace = "http://www.prefeitura.sp.gov.br/nfe")
public class RetornoConsulta implements Serializable {

	@XmlElement(name = "Cabecalho", required = true)
	protected RetornoConsulta.Cabecalho cabecalho;
	@XmlElement(name = "Alerta")
	protected List<TpEvento> alerta;
	@XmlElement(name = "Erro")
	protected List<TpEvento> erro;
	@XmlElement(name = "NFe")
	protected List<TpNFe> nFe;

	/**
	 * Gets the value of the cabecalho property.
	 * 
	 * @return possible object is {@link RetornoConsulta.Cabecalho }
	 * 
	 */
	public RetornoConsulta.Cabecalho getCabecalho() {
		return cabecalho;
	}

	/**
	 * Sets the value of the cabecalho property.
	 * 
	 * @param value
	 *            allowed object is {@link RetornoConsulta.Cabecalho }
	 * 
	 */
	public void setCabecalho(RetornoConsulta.Cabecalho value) {
		this.cabecalho = value;
	}

	/**
	 * Gets the value of the alerta property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the alerta property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAlerta().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link TpEvento }
	 * 
	 * 
	 */
	public List<TpEvento> getAlerta() {
		if (alerta == null) {
			alerta = new ArrayList<TpEvento>();
		}
		return this.alerta;
	}

	/**
	 * Gets the value of the erro property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the erro property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getErro().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link TpEvento }
	 * 
	 * 
	 */
	public List<TpEvento> getErro() {
		if (erro == null) {
			erro = new ArrayList<TpEvento>();
		}
		return this.erro;
	}

	/**
	 * Gets the value of the nFe property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the nFe property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getNFe().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link TpNFe }
	 * 
	 * 
	 */
	public List<TpNFe> getNFe() {
		if (nFe == null) {
			nFe = new ArrayList<TpNFe>();
		}
		return this.nFe;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Sucesso" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpSucesso"/>
	 *       &lt;/sequence>
	 *       &lt;attribute name="Versao" use="required" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpVersao" fixed="1" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "sucesso" })
	public static class Cabecalho implements Serializable {

		@XmlElement(name = "Sucesso")
		protected boolean sucesso;
		@XmlAttribute(name = "Versao", required = true)
		protected long versao;

		/**
		 * Gets the value of the sucesso property.
		 * 
		 */
		public boolean isSucesso() {
			return sucesso;
		}

		/**
		 * Sets the value of the sucesso property.
		 * 
		 */
		public void setSucesso(boolean value) {
			this.sucesso = value;
		}

		/**
		 * Gets the value of the versao property.
		 * 
		 */
		public long getVersao() {
			return versao;
		}

		/**
		 * Sets the value of the versao property.
		 * 
		 */
		public void setVersao(long value) {
			this.versao = value;
		}

	}

}
