//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 03:50:08 PM BRT 
//

package br.com.tti.sefaz.nfes.schemas.saopaulo.retornoconsulta;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Tipo que define a chave identificadora de um RPS.
 * 
 * <p>
 * Java class for tpChaveRPS complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tpChaveRPS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InscricaoPrestador" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpInscricaoMunicipal"/>
 *         &lt;element name="SerieRPS" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpSerieRPS" minOccurs="0"/>
 *         &lt;element name="NumeroRPS" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpNumero"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpChaveRPS", propOrder = { "inscricaoPrestador", "serieRPS",
		"numeroRPS" })
public class TpChaveRPS implements Serializable {

	@XmlElement(name = "InscricaoPrestador")
	protected long inscricaoPrestador;
	@XmlElement(name = "SerieRPS")
	protected String serieRPS;
	@XmlElement(name = "NumeroRPS")
	protected long numeroRPS;

	/**
	 * Gets the value of the inscricaoPrestador property.
	 * 
	 */
	public long getInscricaoPrestador() {
		return inscricaoPrestador;
	}

	/**
	 * Sets the value of the inscricaoPrestador property.
	 * 
	 */
	public void setInscricaoPrestador(long value) {
		this.inscricaoPrestador = value;
	}

	/**
	 * Gets the value of the serieRPS property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSerieRPS() {
		return serieRPS;
	}

	/**
	 * Sets the value of the serieRPS property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSerieRPS(String value) {
		this.serieRPS = value;
	}

	/**
	 * Gets the value of the numeroRPS property.
	 * 
	 */
	public long getNumeroRPS() {
		return numeroRPS;
	}

	/**
	 * Sets the value of the numeroRPS property.
	 * 
	 */
	public void setNumeroRPS(long value) {
		this.numeroRPS = value;
	}

}
