//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 03:50:08 PM BRT 
//

package br.com.tti.sefaz.nfes.schemas.saopaulo.retornoconsulta;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Chave de identificação da NF-e.
 * 
 * <p>
 * Java class for tpChaveNFe complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tpChaveNFe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InscricaoPrestador" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpInscricaoMunicipal"/>
 *         &lt;element name="NumeroNFe" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpNumero"/>
 *         &lt;element name="CodigoVerificacao" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpCodigoVerificacao" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpChaveNFe", propOrder = { "inscricaoPrestador", "numeroNFe",
		"codigoVerificacao" })
public class TpChaveNFe implements Serializable {

	@XmlElement(name = "InscricaoPrestador")
	protected long inscricaoPrestador;
	@XmlElement(name = "NumeroNFe")
	protected long numeroNFe;
	@XmlElement(name = "CodigoVerificacao")
	protected String codigoVerificacao;

	/**
	 * Gets the value of the inscricaoPrestador property.
	 * 
	 */
	public long getInscricaoPrestador() {
		return inscricaoPrestador;
	}

	/**
	 * Sets the value of the inscricaoPrestador property.
	 * 
	 */
	public void setInscricaoPrestador(long value) {
		this.inscricaoPrestador = value;
	}

	/**
	 * Gets the value of the numeroNFe property.
	 * 
	 */
	public long getNumeroNFe() {
		return numeroNFe;
	}

	/**
	 * Sets the value of the numeroNFe property.
	 * 
	 */
	public void setNumeroNFe(long value) {
		this.numeroNFe = value;
	}

	/**
	 * Gets the value of the codigoVerificacao property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCodigoVerificacao() {
		return codigoVerificacao;
	}

	/**
	 * Sets the value of the codigoVerificacao property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCodigoVerificacao(String value) {
		this.codigoVerificacao = value;
	}

}
