//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 03:50:08 PM BRT 
//


package br.com.tti.sefaz.nfes.schemas.saopaulo.retornoconsulta;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tpEvento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpEvento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Codigo" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpCodigoEvento"/>
 *         &lt;element name="Descricao" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpDescricaoEvento" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ChaveRPS" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpChaveRPS"/>
 *           &lt;element name="ChaveNFe" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpChaveNFe"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpEvento", propOrder = {
    "codigo",
    "descricao",
    "chaveRPS",
    "chaveNFe"
})
public class TpEvento implements Serializable{

    @XmlElement(name = "Codigo")
    protected short codigo;
    @XmlElement(name = "Descricao")
    protected String descricao;
    @XmlElement(name = "ChaveRPS")
    protected TpChaveRPS chaveRPS;
    @XmlElement(name = "ChaveNFe")
    protected TpChaveNFe chaveNFe;

    /**
     * Gets the value of the codigo property.
     * 
     */
    public short getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     */
    public void setCodigo(short value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the chaveRPS property.
     * 
     * @return
     *     possible object is
     *     {@link TpChaveRPS }
     *     
     */
    public TpChaveRPS getChaveRPS() {
        return chaveRPS;
    }

    /**
     * Sets the value of the chaveRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpChaveRPS }
     *     
     */
    public void setChaveRPS(TpChaveRPS value) {
        this.chaveRPS = value;
    }

    /**
     * Gets the value of the chaveNFe property.
     * 
     * @return
     *     possible object is
     *     {@link TpChaveNFe }
     *     
     */
    public TpChaveNFe getChaveNFe() {
        return chaveNFe;
    }

    /**
     * Sets the value of the chaveNFe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpChaveNFe }
     *     
     */
    public void setChaveNFe(TpChaveNFe value) {
        this.chaveNFe = value;
    }

}
