//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:32:33 AM BRST 
//

package br.com.tti.sefaz.nfes.schemas.saopaulo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cabecalho">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CPFCNPJRemetente" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpCPFCNPJ"/>
 *                   &lt;element name="CPFCNPJ" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpCPFCNPJ"/>
 *                   &lt;element name="Inscricao" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpInscricaoMunicipal" minOccurs="0"/>
 *                   &lt;element name="dtInicio" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="dtFim" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="NumeroPagina" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpNumero"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Versao" use="required" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpVersao" fixed="1" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "cabecalho" })
@XmlRootElement(name = "PedidoConsultaNFePeriodo", namespace = "http://www.prefeitura.sp.gov.br/nfe")
public class PedidoConsultaNFePeriodo {

	@XmlElement(name = "Cabecalho", required = true)
	protected PedidoConsultaNFePeriodo.Cabecalho cabecalho;

	/*
	 * @XmlElement(name = "Signature", namespace =
	 * "http://www.w3.org/2000/09/xmldsig#", required = true) protected
	 * SignatureType signature;
	 */

	/**
	 * Gets the value of the cabecalho property.
	 * 
	 * @return possible object is {@link PedidoConsultaNFePeriodo.Cabecalho }
	 * 
	 */
	public PedidoConsultaNFePeriodo.Cabecalho getCabecalho() {
		return cabecalho;
	}

	/**
	 * Sets the value of the cabecalho property.
	 * 
	 * @param value
	 *            allowed object is {@link PedidoConsultaNFePeriodo.Cabecalho }
	 * 
	 */
	public void setCabecalho(PedidoConsultaNFePeriodo.Cabecalho value) {
		this.cabecalho = value;
	}

	/**
	 * Assinatura digital do tomador das NF-e.
	 * 
	 * @return possible object is {@link SignatureType }
	 * 
	 */
	/*
	 * public SignatureType getSignature() { return signature; }
	 *//**
	 * Assinatura digital do tomador das NF-e.
	 * 
	 * @param value
	 *            allowed object is {@link SignatureType }
	 * 
	 */
	/*
	 * public void setSignature(SignatureType value) { this.signature = value; }
	 */

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="CPFCNPJRemetente" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpCPFCNPJ"/>
	 *         &lt;element name="CPFCNPJ" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpCPFCNPJ"/>
	 *         &lt;element name="Inscricao" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpInscricaoMunicipal" minOccurs="0"/>
	 *         &lt;element name="dtInicio" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *         &lt;element name="dtFim" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *         &lt;element name="NumeroPagina" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpNumero"/>
	 *       &lt;/sequence>
	 *       &lt;attribute name="Versao" use="required" type="{http://www.prefeitura.sp.gov.br/nfe/tipos}tpVersao" fixed="1" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "cpfcnpjRemetente", "cpfcnpj",
			"inscricao", "dtInicio", "dtFim", "numeroPagina" })
	public static class Cabecalho {

		@XmlElement(name = "CPFCNPJRemetente", required = true)
		protected TpCPFCNPJ cpfcnpjRemetente;
		@XmlElement(name = "CPFCNPJ", required = true)
		protected TpCPFCNPJ cpfcnpj;
		@XmlElement(name = "Inscricao")
		protected Long inscricao;
		@XmlElement(required = true)
		@XmlSchemaType(name = "date")
		protected String dtInicio;
		@XmlElement(required = true)
		@XmlSchemaType(name = "date")
		protected String dtFim;
		@XmlElement(name = "NumeroPagina", defaultValue = "1")
		protected long numeroPagina;
		@XmlAttribute(name = "Versao", required = true)
		protected long versao;

		/**
		 * Gets the value of the cpfcnpjRemetente property.
		 * 
		 * @return possible object is {@link TpCPFCNPJ }
		 * 
		 */
		public TpCPFCNPJ getCPFCNPJRemetente() {
			return cpfcnpjRemetente;
		}

		/**
		 * Sets the value of the cpfcnpjRemetente property.
		 * 
		 * @param value
		 *            allowed object is {@link TpCPFCNPJ }
		 * 
		 */
		public void setCPFCNPJRemetente(TpCPFCNPJ value) {
			this.cpfcnpjRemetente = value;
		}

		/**
		 * Gets the value of the cpfcnpj property.
		 * 
		 * @return possible object is {@link TpCPFCNPJ }
		 * 
		 */
		public TpCPFCNPJ getCPFCNPJ() {
			return cpfcnpj;
		}

		/**
		 * Sets the value of the cpfcnpj property.
		 * 
		 * @param value
		 *            allowed object is {@link TpCPFCNPJ }
		 * 
		 */
		public void setCPFCNPJ(TpCPFCNPJ value) {
			this.cpfcnpj = value;
		}

		/**
		 * Gets the value of the inscricao property.
		 * 
		 * @return possible object is {@link Long }
		 * 
		 */
		public Long getInscricao() {
			return inscricao;
		}

		/**
		 * Sets the value of the inscricao property.
		 * 
		 * @param value
		 *            allowed object is {@link Long }
		 * 
		 */
		public void setInscricao(Long value) {
			this.inscricao = value;
		}

		public String getDtInicio() {
			return dtInicio;
		}

		public void setDtInicio(String dtInicio) {
			this.dtInicio = dtInicio;
		}

		public String getDtFim() {
			return dtFim;
		}

		public void setDtFim(String dtFim) {
			this.dtFim = dtFim;
		}

		/**
		 * Gets the value of the numeroPagina property.
		 * 
		 */
		public long getNumeroPagina() {
			return numeroPagina;
		}

		/**
		 * Sets the value of the numeroPagina property.
		 * 
		 */
		public void setNumeroPagina(long value) {
			this.numeroPagina = value;
		}

		/**
		 * Gets the value of the versao property.
		 * 
		 */
		public long getVersao() {
			return versao;
		}

		/**
		 * Sets the value of the versao property.
		 * 
		 */
		public void setVersao(long value) {
			this.versao = value;
		}

	}

}
